name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        cd client && npm install
        cd ../server && npm install

    - name: Run Cypress tests
      run: |
        cd client && npm run test:cypress

    - name: Upload Cypress results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: client/cypress/results/
