name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Backend Deployment on Render
        run: |
          if [ -z "${{ secrets.RENDER_BACKEND_HOOK_URL }}" ]; then
            echo "ERROR: RENDER_BACKEND_HOOK_URL is not set"
            exit 1
          fi
          curl -X POST "${{ secrets.RENDER_BACKEND_HOOK_URL }}"

      - name: Trigger Frontend Deployment on Render
        run: |
          if [ -z "${{ secrets.RENDER_FRONTEND_HOOK_URL }}" ]; then
            echo "ERROR: RENDER_FRONTEND_HOOK_URL is not set"
            exit 1
          fi
          curl -X POST "${{ secrets.RENDER_FRONTEND_HOOK_URL }}"
