name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Backend Deployment on Render
        run: |
          curl -X POST "$RENDER_BACKEND_HOOK_URL"

      - name: Trigger Frontend Deployment on Render
        run: |
          curl -X POST "$RENDER_FRONTEND_HOOK_URL"
